### PR TITLE
fix issue 126 by setting receiver settlement mode on sender

### LINKED ISSUE #126: Missing events in EventHub after successful send
### Expected Behavior

We expect that all events are delivered to the EventHub.

### Actual Behavior

However, if EventHub returns any error during receiving of messages from the sender (e.g. in case the throughput limits are exceeded), the sender is not notified of that situation immediately. Several events are lost before the connection becomes healthy again. 

We believe the issue might be caused by the fact that EventHub does not support acknowledging the event upon obtaining it. Therefore, the sender keeps sending the messages until it receives the error notification from EventHub (which takes some time) and when it reconnects, it continues sending messages from the last one that was sent (and not the first one that caused the error). 

We are not sure about a possible solution as this involves several components. In an ideal scenario, EventHub could respond to the new event by acknowledging it (or also to each batch by acknowledging it).

The current situation is for us quite problematic, as we cannot go to production with the risk of our events getting lost and we are not getting notified about it.

Do you have any ideas what could be done to mitigate the situation?

### Environment
- OS: AKS, Ubuntu 16.04
- Go version: v1.12
- Version of library: v2.0.0

### Replication of the problem

```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/Azure/azure-event-hubs-go/v2"
)

func main() {
	partitionID := "0"
	eventNum := int64(15000)
	connStr := "Endpoint=sb://namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=superSecret1234=;EntityPath=hubName"
	hub, err := eventhub.NewHubFromConnectionString(connStr, eventhub.HubWithPartitionedSender(partitionID))

	if err != nil {
		fmt.Println(err)
		return
	}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	partitionInfo0, err := hub.GetPartitionInformation(ctx, partitionID)
	if err != nil {
		fmt.Println(err)
		return
	}

	event := eventhub.NewEventFromString("hello, world!")
	for i := int64(0); i < eventNum; i++ {
		err = hub.Send(ctx, event)
		if err != nil {
			fmt.Println(err)
			return
		}
	}

	partitionInfo1, err := hub.GetPartitionInformation(ctx, partitionID)
	if err != nil {
		fmt.Println(err)
		return
	}

	if partitionInfo1.LastSequenceNumber - partitionInfo0.LastSequenceNumber != eventNum {
		// Always if eventhub is throttled
		fmt.Printf("Test failed, number of received events: %d (expected=%d)",
			partitionInfo1.LastSequenceNumber - partitionInfo0.LastSequenceNumber, eventNum)
	} else {
		// Only if eventhub is not throttled
		fmt.Println("Test success")
	}

	err = hub.Close(context.Background())
	if err != nil {
		fmt.Println(err)
	}
}
```

### PR DESCRIPTION
**Pull request by devigned**
Sender should request the receiver send an ack on messages.

fixes #126

- [x] All tests passed
- [x] Add change to `changelog.md`

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
@nemakam Is this what the suggested way to create a sender link is? i.e to set the `receiver-settle-mode` to second (i.e value 1) when creating the sender link?

**Comment by ramya-rao-a** [comment]
@devigned Do you plan to make the same fix for Service Bus?

**Comment by gavinfish** [comment]
@devigned this PR is blocked by the license/cla step.

**Comment by devigned** [comment]
I’ll get this fixed this morning. Looks like my EH instance was ok with second, but the test instance is not ok with it. This might be behavior we need to bring up with EH team.

**Comment by devigned** [comment]
Here's what I get when I run my test locally with the sender specifying `ReceiverSettleMode: second`

```
08:52:44.619636 RX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
08:52:44.691883 TX: Begin{RemoteChannel: 0, NextOutgoingID: 0, IncomingWindow: 100, OutgoingWindow: 100, HandleMax: 4294967295, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:52:44.764032 RX: Begin{RemoteChannel: 1, NextOutgoingID: 1, IncomingWindow: 5000, OutgoingWindow: 100, HandleMax: 255, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:52:44.764104 TX: Attach{Name: 5SGhHXtC4pzwUrBXthtszA5hx6nn9-GQZ8ui1u952bkCFGWTJkQRNg, Handle: 0, Role: Sender, SenderSettleMode: unsettled, ReceiverSettleMode: second, Source: <nil>, Target: source{Address: goehtestbkls6s-tagfoa74/Partitions/0, Durable: 0, ExpiryPolicy: , Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 0, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:52:44.931633 RX(Session): Attach{Name: 5SGhHXtC4pzwUrBXthtszA5hx6nn9-GQZ8ui1u952bkCFGWTJkQRNg, Handle: 0, Role: Receiver, SenderSettleMode: unsettled, ReceiverSettleMode: second, Source: <nil>, Target: source{Address: goehtestbkls6s-tagfoa74/Partitions/0, Durable: 0, ExpiryPolicy: session-end, Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 1046528, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:52:44.931659 RX(Session): Flow{NextIncomingID: 0, IncomingWindow: 5000, NextOutgoingID: 1, OutgoingWindow: 100, Handle: 0, DeliveryCount: 0, LinkCredit: 1000, Available: 0, Drain: false, Echo: false, Properties: map[]}
08:52:44.931709 RX: Attach{Name: 5SGhHXtC4pzwUrBXthtszA5hx6nn9-GQZ8ui1u952bkCFGWTJkQRNg, Handle: 0, Role: Receiver, SenderSettleMode: unsettled, ReceiverSettleMode: second, Source: <nil>, Target: source{Address: goehtestbkls6s-tagfoa74/Partitions/0, Durable: 0, ExpiryPolicy: session-end, Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 1046528, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:52:44.931887 RX: Flow{NextIncomingID: 0, IncomingWindow: 5000, NextOutgoingID: 1, OutgoingWindow: 100, Handle: 0, DeliveryCount: 0, LinkCredit: 1000, Available: 0, Drain: false, Echo: false, Properties: map[]}
08:52:44.931905 TX(link): Transfer{Handle: 0, DeliveryID: 1, DeliveryTag: "\x00\x00\x00\x00\x00\x00\x00\x00", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 72}
08:52:44.931918 TX(Session): Transfer{Handle: 0, DeliveryID: 1, DeliveryTag: "\x00\x00\x00\x00\x00\x00\x00\x00", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 72}
08:52:45.044958 RX(Session): Disposition{Role: Receiver, First: 1, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
08:52:45.044987 RX: Disposition{Role: Receiver, First: 1, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
08:52:45.045103 TX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
08:52:45.118691 RX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
```

Here's what I get when I run my test locally with the sender specifying `ReceiverSettleMode: first`
```
08:55:55.974112 TX: Begin{RemoteChannel: 0, NextOutgoingID: 0, IncomingWindow: 100, OutgoingWindow: 100, HandleMax: 4294967295, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:55:56.046541 RX: Begin{RemoteChannel: 1, NextOutgoingID: 1, IncomingWindow: 5000, OutgoingWindow: 100, HandleMax: 255, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:55:56.046808 TX: Attach{Name: 6y7CH0BLEY-9MJZRONiM_Cx8kVVjrOsH65epiR56Jpcrqr9R1aJxyg, Handle: 0, Role: Sender, SenderSettleMode: unsettled, ReceiverSettleMode: first, Source: <nil>, Target: source{Address: goehtesthnsuzs-tagt5psf/Partitions/0, Durable: 0, ExpiryPolicy: , Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 0, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:55:56.208949 RX(Session): Attach{Name: 6y7CH0BLEY-9MJZRONiM_Cx8kVVjrOsH65epiR56Jpcrqr9R1aJxyg, Handle: 0, Role: Receiver, SenderSettleMode: unsettled, ReceiverSettleMode: first, Source: <nil>, Target: source{Address: goehtesthnsuzs-tagt5psf/Partitions/0, Durable: 0, ExpiryPolicy: session-end, Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 1046528, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:55:56.209045 RX(Session): Flow{NextIncomingID: 0, IncomingWindow: 5000, NextOutgoingID: 1, OutgoingWindow: 100, Handle: 0, DeliveryCount: 0, LinkCredit: 1000, Available: 0, Drain: false, Echo: false, Properties: map[]}
08:55:56.209171 RX: Attach{Name: 6y7CH0BLEY-9MJZRONiM_Cx8kVVjrOsH65epiR56Jpcrqr9R1aJxyg, Handle: 0, Role: Receiver, SenderSettleMode: unsettled, ReceiverSettleMode: first, Source: <nil>, Target: source{Address: goehtesthnsuzs-tagt5psf/Partitions/0, Durable: 0, ExpiryPolicy: session-end, Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 1046528, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
08:55:56.209607 RX: Flow{NextIncomingID: 0, IncomingWindow: 5000, NextOutgoingID: 1, OutgoingWindow: 100, Handle: 0, DeliveryCount: 0, LinkCredit: 1000, Available: 0, Drain: false, Echo: false, Properties: map[]}
08:55:56.209655 TX(link): Transfer{Handle: 0, DeliveryID: 1, DeliveryTag: "\x00\x00\x00\x00\x00\x00\x00\x00", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 72}
08:55:56.209692 TX(Session): Transfer{Handle: 0, DeliveryID: 1, DeliveryTag: "\x00\x00\x00\x00\x00\x00\x00\x00", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 72}
08:55:56.210047 TX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
08:55:56.280873 RX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
```

You can see that with ReceiverSettleMode set to second, `08:52:45.044987 RX: Disposition{Role: Receiver, First: 1, Last: <nil>, Settled: true, State: Accepted, Batchable: false}` the disposition is received for the sent message. When ReceiverSettleMode is set to first, the disposition is not received.

Per the specification for [ReceiverSettleMode](http://docs.oasis-open.org/amqp/core/v1.0/csprd01/amqp-core-transport-v1.0-csprd01.html#type-receiver-settle-mode), this is the expected behavior.

The fact the tests are not replicating this behavior is quite unsettling (see what I did there...). I believe this is a server side issue and needs some attention.

/cc @ramya-rao-a @sjkwak

**Comment by devigned** [comment]
@ramya-rao-a, we need to check what the server decides for default ReceiverSettleMode when not specified by the sender. At this point, we just let the server default by not specifying it on the link attach. If the server is doing the Right Thing™, then it should just work.

**Comment by devigned** [comment]
@vcabbage I'm thinking more and more about how send confirmations are handled, and I'm not sure it's being handled correctly here https://github.com/vcabbage/amqp/blob/ad1b5de89c76150682c92e06cba5a7024f122f14/client.go#L414-L445.

I think the logic should be `if !message.settled { waitForConfirmation }`. That way if the sender is in (SSM mixed and message is unsettled) or (SSM unsettled), a disposition would be expected from the broker. What do you think?

That then begs the question, in mixed mode, should a consumer be able to mark a message as settled / unsettled?

**Comment by vcabbage** [comment]
@devigned I think you're right. Here's what I can discern from the documentation below:

* SSM=settled: overrides RSM; no acks.
* SSM=unsettled: sender should wait for receiver to ack
* RSM=first: receiver considers it settled immediately, but must still send ack (SSM=unsettled only)
* RSM=second: receiver sends ack and waits for return ack from sender (SSM=unsettled only)

Adding support for specifying per-message when SSM=mixed makes sense to me.

[transfer](http://docs.oasis-open.org/amqp/core/v1.0/csprd01/amqp-core-transport-v1.0-csprd01.html#type-transfer) fields:

`settled`:

> If the negotiated value for snd-settle-mode at attachment is settled, then this field MUST be true on at least one transfer frame for a delivery (i.e., the delivery must be settled at the sender at the point the delivery has been completely transferred).
>
> If the negotiated value for snd-settle-mode at attachment is unsettled, then this field MUST be false (or unset) on every transfer frame for a delivery (unless the delivery is aborted). 

`rcv-settle-mode`:

> If first, this indicates that the receiver MUST settle the delivery once it has arrived without waiting for the sender to settle first.
> 
> If second, this indicates that the receiver MUST NOT settle until sending its disposition to the sender and receiving a settled disposition from the sender.
> 
> If not set, this value is defaulted to the value negotiated on link attach.
> 
> If the negotiated link value is first, then it is illegal to set this field to second.
> 
> If the message is being sent settled by the sender, the value of this field is ignored.

**Comment by devigned** [comment]
@vcabbage that sounds right. 

@xinchen10 do you see any issues in @vcabbage's logic above?

**Comment by xinchen10** [comment]
Looks fine to me. For Service Bus and Event Hubs, a sending client is expected to set ssm=unsettled,rsm=first, though some other combinations may work. Today we are not strictly checking for invalid combinations.

**Pull request merged**
