### PR TITLE
Memory persister fail-passes with an empty checkpoint store

### PR DESCRIPTION
**Pull request by richardpark-msft**
The MemoryPersister was returning both an error and a valid return value when a checkpoint is first being requested.

In other languages, at least, this is not an error condition at all and it's perfectly fine (it's the default state of the checkpoint store before any checkpoints have been committed). Since this is the in memory persister it'll always start off empty.

Changing to only return the checkpoint and to remove the error. This blows up the default readme sample and (as far as I know) language conventions as well.

### CODE REVIEW

**Comment by devigned** [comment]
I think you might need to also update: https://github.com/Azure/azure-event-hubs-go/blob/717fe444f26da332e23657da0a9e5de441bb249f/receiver.go#L426-L438

**Comment by richardpark-msft** [comment]
Thanks @devigned, looking at this some more I realize I'm unravelling something less obvious than I thought it was.

In particular, after you pointed me to the receiver I looked at the other persisters and some of them make a similar assumption (return an error and a successful result). Let me check on this a bit more.

Although at least I did get the formatting of the code correct. :)

**Comment by devigned** [comment]
IIRC, we thought about returning `ok bool`, but decided that `error` might make more sense in some situations so that we could disambiguate an error reading and not finding an initial checkpoint, an empty read.

**Comment by richardpark-msft** [comment]
Yeah, looking at this some more I'm nervous to boil the ocean for a simple fix. Let me see if I can make the calling code aware of this convention so it doesn't return the error back to the user.

I suppose ideally we could at least return the same error for "I created a new one because it didn't exist" so it's distinguishable but that might not be necessary in practice.

**Comment by richardpark-msft** [comment]
> 
> 
> IIRC, we thought about returning `ok bool`, but decided that `error` might make more sense in some situations so that we could disambiguate an error reading and not finding an initial checkpoint, an empty read.

Okay, I looked at this some more and I feel considerably less nervous. :)

From what I can see there are basically 4 implementations of these persistors (two in EPH, and two just non-EPH ones). The `MemoryPersister` is the only one that appears to return the a checkpoint and an error where it expects the error to essentially be ignored.

I've changed the behavior here now so that memory persister no longer does this. 

Looking at `receiver.go` as @devigned mention above I realized that the filters generated in both cases are basically the same so I can remove the 'error' case, provided we were okay with always doing a `>` and not a `>=`.

Prior to my change for non-errors we were doing `>` (ie: non-inclusive of the offset) and `>=` for the 'error' case, where the offset would have been -1. Since offsets always start at 0 for Event Hubs we are safe to just always use `>`, since `> -1` will also take us to the right event.

@devigned , @jhendrixMSFT - does this logic seem right to you?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
