### PR TITLE
EventBatchIterator is longer stuck in a loop if the message batch exceeds the default max size

### PR DESCRIPTION
**Pull request by christiannicola**
### Fix

- [x] All tests passed
- [ ] Add change to `changelog.md`

### Environment
- OS: macOS 10.15.6
- Go version: 1.15

### CODE REVIEW

**Comment by jonasrichard** [comment]
We may have the same issue. Is there anything which hold you back merging this PR?

**Comment by jonasrichard** [comment]
Event the first loop is a bit weird however works.

```go
func (ebi *EventBatchIterator) Next(eventID string, opts *BatchOptions) (*EventBatch, error) {
	var key string
	for partitionKey, cursor := range ebi.Cursors {
		if cursor != len(ebi.PartitionEventsMap[partitionKey]) {
			key = partitionKey
                        break    // if we found the partitionKey to be processed, let us not check the other partitionKeys now
		}
	}
	if key == "" {
		return nil, ErrNoMessages{}
	}
...
```

**Comment by christiannicola** [comment]
@jonasrichard Not sure what's the blocker here - I updated the PR because master has changed, however now the pipelines are failing - not entirely sure whats happening here.

**Comment by jonasrichard** [comment]
Some command in the build image is missing.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=582067&view=logs&j=f6772eee-2301-51f0-e883-3630782447bd&t=92716e5b-eb3c-5f92-bc8a-5f7ff8e84fa9

**Comment by christiannicola** [comment]
@jonasrichard Yes I noticed that - but the worker installs the cyclo binary via `go get`. Not sure how to debug / fix this.

**Comment by jonasrichard** [comment]
I found another issue. Let us suppose that one event is bigger than 1MB which is the whole batch limit. In that case the iterator will iterate infinitely over that data item. This is what happened in our cases.

My idea that to watch the mashaledMessages length after a size failure. But in case of this error some messages from the batch may have been sent already and some others won't because of the failure. I think I will handle this error outside of the go-eventhub driver.

```go
	for _, event := range events {
		ok, err := eb.Add(event)
		if err != nil {
			return nil, err
		}

		if !ok {
			if len(eb.marshaledMessages) == 0 {
				return eb, errors.New("message is too big")
			}

			return eb, nil
		}
		ebi.Cursors[key]++
	}
```

**Comment by christiannicola** [comment]
@jonasrichard good catch. Will try to incorporate that fix in my current branch since that will help others a lot I'm sure.

**Comment by jonasrichard** [comment]
@christiannicola  One more thing: in Go map iterators are not stable. So if you make range over a map the order is not certain to be the same as that of the previous run. So even if we fix all of this, the first loop need to be stabilised. Probably an array of events we need to make because the iteration over that is stable.
https://github.com/golang/go/issues/5362

**Comment by jonasrichard** [comment]
@christiannicola You can close this PR, I made another one with the changes I recommended here, and it is merged.

**Pull request closed without merging**
