### PR TITLE
Add IoT Hub System Properties

### PR DESCRIPTION
**Pull request by fischor**
See #160

### CODE REVIEW

**Comment by R290** [comment]
@gavinfish any news on when this might be merged? I'd like to incorporate the iot hub system properties in an plugin I've created: https://github.com/influxdata/telegraf/pull/6928 (the milestone is due for March 16, 2020).

**Comment by gavinfish** [comment]
Assign @jhendrixMSFT who is the owner of this repo.

**Comment by jhendrixMSFT** [comment]
@fischor can you please sign the CLA?  Once that's complete I can merge and tag this.

**Comment by fischor** [comment]
@jhendrixMSFT signed

**Pull request merged**
