### PR TITLE
Fix incorrect cast to string

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Updated Go versions in CI

### Fix or Enhancement?

- [ ] All tests passed
- [ ] Add change to `changelog.md`

### Environment
- OS: Write here
- Go version: Write here

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Fixes https://github.com/Azure/azure-event-hubs-go/issues/195

**Review by catalinaperalta — APPROVED** [review]
LGTM

**Comment by jhendrixMSFT** [comment]
Already addressed in https://github.com/Azure/azure-event-hubs-go/pull/189

**Pull request closed without merging**
