### PR TITLE
update quickstart

### PR DESCRIPTION
**Pull request by atecce**
figured I'd open this after the discussion yesterday day [here](https://github.com/Azure/azure-event-hubs-go/issues/101)!

I know there's probably a lot of things not right but just wanted to start a process

### Fix or Enhancement?

enhanced README

- [ ] All tests passed
- [x] Add change to `changelog.md`

### Environment
- OS: 10.14.3
- Go version: 1.12.1

### CODE REVIEW

**Comment by atecce** [comment]
Screen Shot 2019-04-12 at 9 05 14 AM

fwiw I obviously don't think this would break any tests but I'd _love_ to know what the expectations are for the `.env/` folder. does the test suite actually make any connections to the cloud? do I need an Azure environment to run it?

**Comment by devigned** [comment]
@atecce, sorry for the delay.

The `.env` file contains the environment variables used in the tests. When the test suite starts up, it will load those vars.

The `.env` file should be filled with the following:
```env
AZURE_CLIENT_ID = some_client_id
AZURE_CLIENT_SECRET = some_client_secret
AZURE_SUBSCRIPTION_ID = some_sub_id
AZURE_TENANT_ID = some_tenant_id
EVENTHUB_CONNECTION_STRING = Endpoint=sb://some-hub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=super_secret
EVENTHUB_NAMESPACE = some_hub_namespace
STORAGE_ACCOUNT_NAME = some_storage_account
TEST_EVENTHUB_LOCATION = some_azure_region
TEST_EVENTHUB_RESOURCE_GROUP = some_azure_resource_group
```

The `.env` file is generated / populated by Terraform when `make test` or derivations there of are used (`make test-verbose`, `make test-bench`, etc). Basically, the following is run:
- `terraform init`
- `terraform apply -auto-approve`
- `terraform output > .env`

The Terraform deployment is described in https://github.com/Azure/azure-event-hubs-go/blob/master/azuredeploy.tf. This can be run to create a full environment for running tests and developing on the library.

I have thought about adding recorded tests, but have found it helpful to run the live tests to ensure tests are truthful.

Please let me know if you have any questions. I'm happy to expand upon areas I didn't cover adequately.

**Comment by atecce** [comment]
oh awesome! thank you so much! I will definitely look into standing this stuff up to test this out. <3 Terraform

**Comment by devigned** [comment]
@atecce any chance you'd be interested in retargeting this example to https://github.com/Azure/azure-event-hubs-go/blob/master/hub_examples_test.go. That way, the example will show up in Godocs and be run in the test suite.

I think your example will be particularly helpful as an example of how to send and receive from a particular partition.

**Comment by atecce** [comment]
sure thing!

**Comment by devigned** [comment]
The cool part about the Terraform deployment is that it will provision an Azure identity (application & service principal) if needed and give it the rights needed to talk to Event Hubs. That way the tests can execute with both Azure Active Directory auth as well as connection string auth.

**Comment by atecce** [comment]
that does sound cool. I just finished a grueling argument with Service Principals and it's great you have that captured in revision control :D

**Comment by devigned** [comment]
I'm going to close this PR since the consumer group should not be required. Thank you for submitting the PR and please don't let this dissuade you from submitting another or reopening the issue if you think closing it is in error.

**Comment by atecce** [comment]
np, and sorry! got caught up with a couple other things :D

**Pull request closed without merging**
